### ISSUE TITLE
Working with mongo and modular-odm

### ISSUE THREAD

**Issue by SamPortnow** [CenterForOpenScience/modular-odm#34]
A note that wasn't clear from the examples:

If you are using Flask, In order to use PyMongo and also include your db logic in a models file, you must use the app context to initialize the database, so:

    with app.app_context():
        Text.set_storage(storage.MongoStorage(mongo.db, 'text'))

Might be obvious to more experienced uses of Flask, but wasn't to me initially :).

**Comment by lyndsysimon** [comment]
This is only the case if the model's logic relies on the Flask environment to be present. As it's adequately covered in the Flask docs, I'd rather not include it in the top-level Modular-ODM docs.

That said, we have a `FlaskStoredObject` in the OSF that would be a great place to document this sort of thing should it ever be rolled into Modular-ODM.
